name: Deploy Start Bootstrap Personal to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change if needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: gulp build  # Change if necessary

      - name: Debug working directory
        run: ls -la  # Check what files exist

      - name: Debug build output
        run: ls -la dist || ls -la public  # Check if /dist or /public exists

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist  # Change to public if needed

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
